CREATE TABLE products (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price REAL NOT NULL,
    stock INTEGER DEFAULT 0,
    category TEXT,
    size TEXT,
    color TEXT
);

CREATE TABLE carts (
    id TEXT PRIMARY KEY, 
    user_phone TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT DEFAULT 'active'
);

CREATE TABLE cart_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cart_id TEXT NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER DEFAULT 1,
    FOREIGN KEY (cart_id) REFERENCES carts(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Datos de productos importados del Excel
INSERT INTO products (id, name, description, price, stock, category, size, color) VALUES 
(1, 'Pantalón', 'Ideal para uso diario.', 1058, 177, 'Deportivo', 'XXL', 'Verde'),
(2, 'Camiseta', 'Prenda cómoda y ligera.', 510, 33, 'Deportivo', 'XXL', 'Blanco'),
(3, 'Camiseta', 'Diseño moderno y elegante.', 1292, 457, 'Casual', 'S', 'Negro'),
(4, 'Falda', 'Ideal para uso diario.', 1138, 414, 'Casual', 'S', 'Blanco'),
(5, 'Sudadera', 'Diseño moderno y elegante.', 603, 151, 'Formal', 'XL', 'Verde'),
(6, 'Chaqueta', 'Prenda cómoda y ligera.', 961, 223, 'Deportivo', 'S', 'Amarillo'),
(7, 'Pantalón', 'Diseño moderno y elegante.', 1331, 436, 'Deportivo', 'L', 'Gris'),
(8, 'Falda', 'Prenda cómoda y ligera.', 1286, 441, 'Casual', 'XXL', 'Blanco'),
(9, 'Sudadera', 'Material de alta calidad.', 889, 187, 'Casual', 'L', 'Azul'),
(10, 'Pantalón', 'Diseño moderno y elegante.', 647, 462, 'Formal', 'XXL', 'Gris'),
(11, 'Chaqueta', 'Material de alta calidad.', 464, 65, 'Deportivo', 'S', 'Azul'),
(12, 'Pantalón', 'Material de alta calidad.', 786, 65, 'Formal', 'M', 'Blanco'),
(13, 'Falda', 'Material de alta calidad.', 762, 454, 'Deportivo', 'XL', 'Azul'),
(14, 'Chaqueta', 'Diseño moderno y elegante.', 430, 193, 'Casual', 'L', 'Gris'),
(15, 'Falda', 'Prenda cómoda y ligera.', 952, 246, 'Deportivo', 'L', 'Azul'),
(16, 'Falda', 'Prenda cómoda y ligera.', 883, 301, 'Formal', 'XL', 'Blanco'),
(17, 'Camiseta', 'Material de alta calidad.', 1128, 348, 'Deportivo', 'S', 'Azul'),
(18, 'Falda', 'Prenda cómoda y ligera.', 1224, 39, 'Deportivo', 'L', 'Gris'),
(19, 'Chaqueta', 'Prenda cómoda y ligera.', 416, 86, 'Formal', 'L', 'Azul'),
(20, 'Camiseta', 'Diseño moderno y elegante.', 1292, 302, 'Deportivo', 'XXL', 'Rojo'),
(21, 'Pantalón', 'Material de alta calidad.', 1017, 334, 'Formal', 'L', 'Verde'),
(22, 'Sudadera', 'Diseño moderno y elegante.', 1288, 350, 'Deportivo', 'XL', 'Azul'),
(23, 'Pantalón', 'Prenda cómoda y ligera.', 525, 257, 'Casual', 'S', 'Verde'),
(24, 'Camiseta', 'Diseño moderno y elegante.', 1386, 34, 'Formal', 'M', 'Negro'),
(25, 'Sudadera', 'Perfecta para actividades al aire libre.', 596, 166, 'Deportivo', 'S', 'Negro'),
(26, 'Camiseta', 'Material de alta calidad.', 503, 214, 'Casual', 'S', 'Verde'),
(27, 'Sudadera', 'Ideal para uso diario.', 967, 64, 'Casual', 'S', 'Verde'),
(28, 'Falda', 'Perfecta para actividades al aire libre.', 464, 196, 'Deportivo', 'XL', 'Negro'),
(29, 'Chaqueta', 'Diseño moderno y elegante.', 1465, 282, 'Casual', 'XL', 'Amarillo'),
(30, 'Camisa', 'Ideal para uso diario.', 1100, 206, 'Casual', 'M', 'Verde'),
(31, 'Falda', 'Prenda cómoda y ligera.', 1006, 322, 'Casual', 'XXL', 'Blanco'),
(32, 'Camiseta', 'Perfecta para actividades al aire libre.', 1010, 298, 'Deportivo', 'S', 'Rojo'),
(33, 'Falda', 'Diseño moderno y elegante.', 1120, 482, 'Deportivo', 'M', 'Azul'),
(34, 'Camisa', 'Ideal para uso diario.', 548, 40, 'Formal', 'L', 'Blanco'),
(35, 'Camisa', 'Diseño moderno y elegante.', 783, 264, 'Deportivo', 'XXL', 'Verde'),
(36, 'Sudadera', 'Material de alta calidad.', 1261, 194, 'Deportivo', 'XXL', 'Amarillo'),
(37, 'Sudadera', 'Ideal para uso diario.', 925, 208, 'Formal', 'S', 'Negro'),
(38, 'Pantalón', 'Material de alta calidad.', 1379, 19, 'Formal', 'XXL', 'Rojo'),
(39, 'Pantalón', 'Diseño moderno y elegante.', 1338, 340, 'Casual', 'M', 'Verde'),
(40, 'Pantalón', 'Prenda cómoda y ligera.', 1295, 199, 'Casual', 'M', 'Negro'),
(41, 'Chaqueta', 'Material de alta calidad.', 777, 142, 'Deportivo', 'M', 'Rojo'),
(42, 'Chaqueta', 'Diseño moderno y elegante.', 1089, 333, 'Casual', 'S', 'Amarillo'),
(43, 'Sudadera', 'Perfecta para actividades al aire libre.', 1271, 304, 'Formal', 'XXL', 'Rojo'),
(44, 'Camiseta', 'Diseño moderno y elegante.', 424, 443, 'Deportivo', 'S', 'Azul'),
(45, 'Sudadera', 'Material de alta calidad.', 840, 376, 'Deportivo', 'XL', 'Rojo'),
(46, 'Camisa', 'Perfecta para actividades al aire libre.', 1090, 121, 'Formal', 'S', 'Rojo'),
(47, 'Chaqueta', 'Ideal para uso diario.', 608, 279, 'Formal', 'XL', 'Blanco'),
(48, 'Camiseta', 'Ideal para uso diario.', 548, 480, 'Formal', 'XXL', 'Amarillo'),
(49, 'Sudadera', 'Ideal para uso diario.', 1167, 262, 'Deportivo', 'XL', 'Blanco'),
(50, 'Sudadera', 'Ideal para uso diario.', 717, 248, 'Deportivo', 'XL', 'Blanco'),
(51, 'Falda', 'Diseño moderno y elegante.', 1071, 323, 'Casual', 'M', 'Blanco'),
(52, 'Camisa', 'Material de alta calidad.', 963, 411, 'Casual', 'XXL', 'Gris'),
(53, 'Pantalón', 'Diseño moderno y elegante.', 815, 405, 'Deportivo', 'XL', 'Azul'),
(54, 'Falda', 'Prenda cómoda y ligera.', 805, 41, 'Deportivo', 'L', 'Azul'),
(55, 'Camisa', 'Diseño moderno y elegante.', 551, 111, 'Casual', 'L', 'Blanco'),
(56, 'Chaqueta', 'Perfecta para actividades al aire libre.', 876, 73, 'Formal', 'XL', 'Negro'),
(57, 'Camiseta', 'Diseño moderno y elegante.', 1049, 37, 'Casual', 'S', 'Rojo'),
(58, 'Camisa', 'Diseño moderno y elegante.', 655, 151, 'Casual', 'M', 'Rojo'),
(59, 'Chaqueta', 'Ideal para uso diario.', 1052, 260, 'Deportivo', 'XL', 'Gris'),
(60, 'Pantalón', 'Perfecta para actividades al aire libre.', 960, 405, 'Deportivo', 'M', 'Verde'),
(61, 'Chaqueta', 'Material de alta calidad.', 1055, 297, 'Formal', 'XXL', 'Negro'),
(62, 'Chaqueta', 'Perfecta para actividades al aire libre.', 1180, 473, 'Formal', 'S', 'Verde'),
(63, 'Pantalón', 'Prenda cómoda y ligera.', 708, 11, 'Casual', 'L', 'Rojo'),
(64, 'Falda', 'Material de alta calidad.', 874, 374, 'Deportivo', 'M', 'Gris'),
(65, 'Falda', 'Ideal para uso diario.', 685, 137, 'Casual', 'L', 'Verde'),
(66, 'Camisa', 'Perfecta para actividades al aire libre.', 1151, 441, 'Deportivo', 'XL', 'Azul'),
(67, 'Pantalón', 'Material de alta calidad.', 1331, 17, 'Deportivo', 'XL', 'Azul'),
(68, 'Sudadera', 'Diseño moderno y elegante.', 571, 479, 'Deportivo', 'S', 'Blanco'),
(69, 'Camisa', 'Ideal para uso diario.', 835, 486, 'Deportivo', 'L', 'Negro'),
(70, 'Camiseta', 'Perfecta para actividades al aire libre.', 1225, 364, 'Casual', 'XL', 'Rojo'),
(71, 'Chaqueta', 'Ideal para uso diario.', 1070, 320, 'Casual', 'L', 'Blanco'),
(72, 'Camiseta', 'Diseño moderno y elegante.', 1356, 148, 'Casual', 'L', 'Amarillo'),
(73, 'Falda', 'Material de alta calidad.', 1283, 252, 'Deportivo', 'L', 'Gris'),
(74, 'Pantalón', 'Perfecta para actividades al aire libre.', 913, 28, 'Deportivo', 'XL', 'Rojo'),
(75, 'Chaqueta', 'Ideal para uso diario.', 507, 136, 'Formal', 'S', 'Verde'),
(76, 'Chaqueta', 'Perfecta para actividades al aire libre.', 407, 18, 'Casual', 'L', 'Azul'),
(77, 'Sudadera', 'Diseño moderno y elegante.', 516, 453, 'Formal', 'XL', 'Gris'),
(78, 'Camiseta', 'Prenda cómoda y ligera.', 457, 360, 'Formal', 'M', 'Gris'),
(79, 'Camiseta', 'Ideal para uso diario.', 445, 103, 'Deportivo', 'L', 'Blanco'),
(80, 'Falda', 'Prenda cómoda y ligera.', 680, 200, 'Deportivo', 'S', 'Verde'),
(81, 'Sudadera', 'Diseño moderno y elegante.', 1008, 319, 'Casual', 'M', 'Negro'),
(82, 'Pantalón', 'Diseño moderno y elegante.', 720, 337, 'Formal', 'M', 'Rojo'),
(83, 'Sudadera', 'Material de alta calidad.', 801, 275, 'Casual', 'XXL', 'Azul'),
(84, 'Sudadera', 'Perfecta para actividades al aire libre.', 1167, 218, 'Casual', 'XXL', 'Rojo'),
(85, 'Camisa', 'Material de alta calidad.', 527, 19, 'Casual', 'M', 'Rojo'),
(86, 'Pantalón', 'Perfecta para actividades al aire libre.', 753, 99, 'Casual', 'S', 'Gris'),
(87, 'Falda', 'Ideal para uso diario.', 1390, 317, 'Casual', 'L', 'Verde'),
(88, 'Camisa', 'Material de alta calidad.', 1438, 253, 'Casual', 'M', 'Azul'),
(89, 'Camiseta', 'Perfecta para actividades al aire libre.', 778, 449, 'Formal', 'L', 'Verde'),
(90, 'Camiseta', 'Perfecta para actividades al aire libre.', 404, 350, 'Formal', 'M', 'Verde'),
(91, 'Chaqueta', 'Diseño moderno y elegante.', 463, 98, 'Deportivo', 'XXL', 'Amarillo'),
(92, 'Camiseta', 'Ideal para uso diario.', 987, 226, 'Casual', 'S', 'Gris'),
(93, 'Camiseta', 'Material de alta calidad.', 599, 100, 'Deportivo', 'L', 'Blanco'),
(94, 'Pantalón', 'Diseño moderno y elegante.', 756, 249, 'Casual', 'XL', 'Gris'),
(95, 'Camiseta', 'Perfecta para actividades al aire libre.', 541, 245, 'Formal', 'XL', 'Negro'),
(96, 'Falda', 'Prenda cómoda y ligera.', 975, 480, 'Deportivo', 'L', 'Negro'),
(97, 'Falda', 'Perfecta para actividades al aire libre.', 973, 51, 'Formal', 'XXL', 'Azul'),
(98, 'Sudadera', 'Perfecta para actividades al aire libre.', 1491, 114, 'Casual', 'XXL', 'Azul'),
(99, 'Camiseta', 'Ideal para uso diario.', 1067, 391, 'Formal', 'S', 'Verde'),
(100, 'Chaqueta', 'Diseño moderno y elegante.', 1117, 347, 'Deportivo', 'XL', 'Rojo');